-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 15:06:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema second_handportal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema second_handportal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `second_handportal` DEFAULT CHARACTER SET utf8 ;
USE `second_handportal` ;

-- -----------------------------------------------------
-- Table `second_handportal`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `second_handportal`.`person` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `passwort` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telefonnummer` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `second_handportal`.`zustand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `second_handportal`.`zustand` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `zustand` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `second_handportal`.`artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `second_handportal`.`artikel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bezeichnung` VARCHAR(45) NULL DEFAULT NULL,
  `beschreibung` VARCHAR(45) NULL DEFAULT NULL,
  `preis` DOUBLE NULL DEFAULT NULL,
  `einstelldatum` TIMESTAMP NULL DEFAULT NULL,
  `Person_Personid` INT(11) NOT NULL,
  `Zustand_Zustandid` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Artikel_Person_idx` (`Person_Personid` ASC),
  INDEX `fk_Artikel_Zustand1_idx` (`Zustand_Zustandid` ASC),
  CONSTRAINT `fk_Artikel_Person`
    FOREIGN KEY (`Person_Personid`)
    REFERENCES `second_handportal`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artikel_Zustand1`
    FOREIGN KEY (`Zustand_Zustandid`)
    REFERENCES `second_handportal`.`zustand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
